# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Nguyen T. Su
title: Software Engineer
email: vnntsu@gmail.com
phone: +84 702 35 2040
website: sunguyen.dev
# quote: "Life is like riding a bicycle. To keep your balance you must keep moving!" --- Albert Einstein

# Social links
github_username:  vnntsu
twitter_username: vnntsu
linkedin_username: vnntsu
facebook_username: vnntsu

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Su and I'm a Software Engineer with over 4 years experience. I worked with <mark>iOS</mark> most of that time.
  Currently, I am working at home as a Freelancer.

  I am eager to be challenged in order to grow and further improve my IT skills. I am always looking for opportunities to work with something new. 

  The things that I currently have the most experience working with are: <mark>iOS</mark> <mark>ES6 Javascript</mark>, <mark>Java</mark>, <mark>SQL</mark>, <mark>git</mark>, <mark>CD/CI</mark> and <mark>AWS</mark> services.
about_quote: >
  "Life is like riding a bicycle. To keep your balance you must keep moving!" --- Albert Einstein 


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Like a said, I am always excited to be learn new technical skills. 
  Some of them are <mark>Machine Learning</mark>, <mark>Data Science</mark>, <mark>DevOps</mark>, etc.

  When I’m not sat at my desk I am very active and spend most of my time outdoors. 
  I do a lot a sports such as Football, Table Tennis, Workout, etc.

  Finally during the rest of my free time I always spend this time with my family and friends.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
