title:             Su Nguyen
email:             vnntsu@gmail.com
description:       iOS Engineer
author:            vnntsu
url:               "http://vnntsu.github.io"
email:             vnntsu@gmail.com

# Social Profiles
twitter_username:  vnntsu
github_username:   vnntsu
facebook_username: vnntsu

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
